import type { CompositeInput } from './compositePlayEngine';
import type { DurableScoringScope } from './scoringScope';
import { scoringScopeKey } from './scoringScope';
import type { DurableScoringWriter } from './durableScoringWriter';
import { scoringCheckpoint } from './scoringCheckpoint';
import { hasOfficialAuthority } from './recordSourcePolicy';

type IntakeState = {
  activeMatchId?: string | null;
  events: Array<{ eventId?: string; compositePlay?: unknown }>;
  feed: unknown[];
  history?: unknown;
  futureHistory?: unknown;
  scorerUid?: string | null;
  scorerPaused?: boolean;
  gameStarted?: boolean;
  gameOver?: boolean;
  matches?: Array<{ id: string; status?: string; recordAuthority?: string }>;
};

export type CompositeIntakePort<State extends IntakeState> = {
  capture(): State;
  /** Must check current owner, session, pause, and game lifecycle. */
  validate(state: State, input: CompositeInput): void;
  /** Use the real reducer, not a separately implemented scoring engine. */
  project(state: State, input: CompositeInput): State;
  /** Synchronous compare-and-apply; must throw without mutation on mismatch. */
  apply(before: State, after: State): void;
};

// Superseded full-state checkpoint implementation, retained for migration reference:
// const copy = { ...state }; delete copy.history; delete copy.futureHistory; return copy;
const checkpoint = scoringCheckpoint;

async function fingerprint(value: string): Promise<string> {
  const bytes = await crypto.subtle.digest('SHA-256', new TextEncoder().encode(value));
  return Array.from(new Uint8Array(bytes), byte => byte.toString(16).padStart(2, '0')).join('');
}

function comparable(value: unknown): string {
  const sort = (item: unknown): unknown => {
    if (Array.isArray(item)) return item.map(sort);
    if (item && typeof item === 'object') return Object.fromEntries(Object.entries(item)
      .filter(([, child]) => child !== undefined).sort(([a], [b]) => a.localeCompare(b)).map(([key, child]) => [key, sort(child)]));
    return item;
  };
  return JSON.stringify(sort(value));
}

function replayComparable<State extends IntakeState>(state: State): string {
  const copy = checkpoint(state);
  // Only row creation times are regenerated by replay. Keep all scoring facts.
  const stripTime = (row: unknown) => {
    if (!row || typeof row !== 'object') return row;
    const copy = { ...row } as Record<string, unknown>;
    delete copy.createdAt;
    return copy;
  };
  return comparable({ ...copy, events: copy.events.map(stripTime), feed: copy.feed.map(stripTime) });
}

export type DurableRecoveryItem = {
  inputId: string; sequence: number; status: 'pending' | 'applied' | 'invalid'; summary: string;
};
export type DurableRecoveryController = {
  inspectRecovery(): Promise<DurableRecoveryItem[]>;
  recoverInput(inputId: string): Promise<void>;
};

type IntakeWriter = Pick<DurableScoringWriter, 'stage' | 'confirmApplied' | 'review' | 'assertScope'>;

/** Opt-in intake only. Does not mount a Provider, send RPCs, or restore UI on reload. */
export class DurableCompositeIntake<State extends IntakeState> {
  private readonly writer: IntakeWriter;
  private readonly scope: DurableScoringScope;
  private readonly port: CompositeIntakePort<State>;
  private busy = false;
  private readonly completed = new Map<string, { inputHash: string; afterHash: string }>();
  private readonly attempts = new Map<string, {
    inputJson: string; before: State; after: State; payload: string; applied: boolean;
  }>();

  /** Counts only; never expose retained player data or state history. */
  retentionSummary(): { pendingSnapshots: number; completedFingerprints: number } {
    return { pendingSnapshots: this.attempts.size, completedFingerprints: this.completed.size };
  }

  private async finish(inputId: string, inputJson: string, after: State, payload: string): Promise<void> {
    const receipt = { inputHash: await fingerprint(inputJson), afterHash: await fingerprint(comparable(checkpoint(after))) };
    await this.writer.confirmApplied(inputId, payload);
    this.completed.set(inputId, receipt);
    // Legacy: completed attempts retained before/after, including full undo history.
    this.attempts.delete(inputId);
  }

  constructor(scope: DurableScoringScope, writer: IntakeWriter,
    port: CompositeIntakePort<State>) {
    writer.assertScope(scope);
    this.scope = structuredClone(scope);
    this.writer = writer;
    this.port = port;
  }

  private validateAccess(state: State, input: CompositeInput): void {
    if (state.activeMatchId !== this.scope.matchId) throw new Error('durable-intake-match-mismatch');
    if ((state.scorerUid !== undefined && state.scorerUid !== this.scope.uid) || state.scorerPaused
      || state.gameStarted === false || state.gameOver) throw new Error('durable-intake-access-denied');
    if (state.matches) {
      const active = state.matches.find(match => match.id === this.scope.matchId);
      if (!active || active.status === 'completed' || active.status === 'canceled' || hasOfficialAuthority(active)) {
        throw new Error('durable-intake-access-denied');
      }
    }
    // The host still must verify authenticated UID, role, writer session and epoch.
    this.port.validate(state, input);
  }

  async accept(input: CompositeInput): Promise<void> {
    if (this.busy) throw new Error('durable-intake-busy');
    this.busy = true;
    try {
      const frozen = structuredClone(input);
      const inputJson = JSON.stringify(frozen);
      const completed = this.completed.get(frozen.id);
      if (completed) {
        if (await fingerprint(inputJson) !== completed.inputHash) throw new Error('input-id-conflict');
        const recovered = await this.writer.review();
        if (recovered.metadata.blockedReason) throw new Error('queue-blocked');
        if (recovered.metadata.inputReceipts?.[frozen.id]?.localApplication !== 'applied') {
          throw new Error('local-application-review-required');
        }
        const current = structuredClone(this.port.capture());
        this.validateAccess(current, frozen);
        if (await fingerprint(comparable(checkpoint(current))) !== completed.afterHash) throw new Error('durable-intake-state-changed');
        const latest = this.port.capture();
        this.validateAccess(latest, frozen);
        if (comparable(checkpoint(latest)) !== comparable(checkpoint(current))) throw new Error('durable-intake-state-changed');
        return;
      }
      let attempt = this.attempts.get(frozen.id);
      if (attempt && attempt.inputJson !== inputJson) throw new Error('input-id-conflict');
      const current = structuredClone(this.port.capture());
      if (current.activeMatchId !== this.scope.matchId) throw new Error('durable-intake-match-mismatch');
      this.validateAccess(current, frozen);
      if (attempt?.applied) {
        if (comparable(checkpoint(current)) !== comparable(checkpoint(attempt.after))) throw new Error('durable-intake-state-changed');
        await this.finish(frozen.id, attempt.inputJson, attempt.after, attempt.payload);
        return;
      }
      const recovered = await this.writer.review();
      if (recovered.metadata.blockedReason) throw new Error('queue-blocked');
      const latestInput = recovered.inputs.at(-1);
      if (latestInput?.inputId === frozen.id) {
        // Only an in-memory retry may reuse its original projection here.
        // After reload, use explicit recovery rather than regenerate the payload.
        if (!attempt) throw new Error('recovery-required-before-input');
        if (latestInput.snapshot !== attempt.payload) throw new Error('input-id-conflict');
      } else if (latestInput) {
        if (recovered.metadata.inputReceipts?.[latestInput.inputId]?.localApplication !== 'applied') {
          throw new Error('local-application-review-required');
        }
        const previous = this.decode(latestInput.snapshot, latestInput.inputId);
        if (comparable(checkpoint(current)) !== comparable(checkpoint(previous.after))) {
          throw new Error('recovery-required-before-input');
        }
      }
      // Queue inspection is asynchronous: recheck state and authority before projection.
      const inspected = this.port.capture();
      if (comparable(checkpoint(current)) !== comparable(checkpoint(inspected))) throw new Error('durable-intake-state-changed');
      this.validateAccess(inspected, frozen);
      if (!attempt) {
        if (current.events.some(event => event.eventId === frozen.id)) throw new Error('durable-intake-existing-event');
        const before = structuredClone(inspected);
        const after = structuredClone(this.port.project(structuredClone(before), frozen));
        if (after.activeMatchId !== this.scope.matchId
          || after.events.filter(event => event.eventId === frozen.id && event.compositePlay).length !== 1) {
          throw new Error('durable-intake-projection-rejected');
        }
        const payload = JSON.stringify({ version: 1, checkpointVersion: 2, kind: 'composite-play', scope: this.scope,
          input: frozen, before: checkpoint(before), after: checkpoint(after) });
        attempt = { inputJson, before, after, payload, applied: false };
        this.attempts.set(frozen.id, attempt);
      }
      if (comparable(checkpoint(inspected)) !== comparable(checkpoint(attempt.before))) throw new Error('durable-intake-state-changed');
      await this.writer.stage(frozen.id, attempt.payload);
      const latest = this.port.capture();
      if (comparable(checkpoint(latest)) !== comparable(checkpoint(attempt.before))) throw new Error('durable-intake-state-changed');
      this.validateAccess(latest, frozen);
      // Rebuild history from the current host state, keeping current access/ambient fields.
      const replayed = this.port.project(structuredClone(latest), structuredClone(frozen));
      if (replayComparable(replayed) !== replayComparable(attempt.after)) throw new Error('durable-intake-projection-changed');
      this.port.apply(structuredClone(latest), { ...replayed, ...structuredClone(checkpoint(attempt.after)) });
      attempt.applied = true;
      await this.finish(frozen.id, attempt.inputJson, attempt.after, attempt.payload);
    } finally {
      this.busy = false;
    }
  }

  private decode(snapshot: string, inputId: string): { input: CompositeInput; before: State; after: State } {
    const saved = JSON.parse(snapshot);
    if (saved?.version !== 1 || (saved.checkpointVersion !== undefined && saved.checkpointVersion !== 2)
      || saved.kind !== 'composite-play' || saved.input?.id !== inputId
      || scoringScopeKey(saved.scope) !== scoringScopeKey(this.scope)
      || saved.before?.activeMatchId !== this.scope.matchId || saved.after?.activeMatchId !== this.scope.matchId
      || !Array.isArray(saved.before.events) || !Array.isArray(saved.after.events)
      || !Array.isArray(saved.before.feed) || !Array.isArray(saved.after.feed)) throw new Error('invalid-recovery-checkpoint');
    return saved;
  }

  async inspectRecovery(): Promise<DurableRecoveryItem[]> {
    const recovered = await this.writer.review();
    return recovered.inputs.map(row => {
      try {
        const saved = this.decode(row.snapshot, row.inputId);
        const receipt = recovered.metadata.inputReceipts?.[row.inputId];
        if (receipt?.localApplication !== 'pending' && receipt?.localApplication !== 'applied') throw new Error('invalid-recovery-receipt');
        return { inputId: row.inputId, sequence: row.sequence, status: receipt.localApplication,
          summary: `${saved.input.expected.inning}회 ${saved.input.expected.half === 'top' ? '초' : '말'} · ${saved.input.expected.batterId} · ${saved.input.plate}` };
      } catch {
        return { inputId: row.inputId, sequence: row.sequence, status: 'invalid', summary: '복구 형식 또는 범위 확인 필요' };
      }
    });
  }

  async recoverInput(inputId: string): Promise<void> {
    if (this.busy) throw new Error('durable-intake-busy');
    this.busy = true;
    try {
      const recovered = await this.writer.review();
      if (recovered.metadata.blockedReason) throw new Error('queue-blocked');
      const row = recovered.inputs.find(input => input.inputId === inputId);
      if (!row) throw new Error('recovery-input-not-found');
      if (recovered.inputs.some(input => input.sequence < row.sequence
        && recovered.metadata.inputReceipts?.[input.inputId]?.localApplication !== 'applied')) throw new Error('recovery-order-required');
      const saved = this.decode(row.snapshot, inputId);
      const current = structuredClone(this.port.capture());
      if (current.activeMatchId !== this.scope.matchId) throw new Error('durable-intake-match-mismatch');
      this.validateAccess(current, saved.input);
      if (comparable(checkpoint(current)) !== comparable(checkpoint(saved.after))) {
        if (comparable(checkpoint(current)) !== comparable(checkpoint(saved.before))) throw new Error('recovery-state-conflict');
        const replayed = this.port.project(structuredClone(current), structuredClone(saved.input));
        if (replayed.events.filter(event => event.eventId === inputId && event.compositePlay).length !== 1
          || replayComparable(replayed) !== replayComparable(saved.after)) throw new Error('recovery-replay-mismatch');
        // Keep persisted timestamps/facts; obtain undo/redo history from the real reducer.
        const restored = { ...replayed, ...checkpoint(saved.after) };
        this.validateAccess(this.port.capture(), saved.input);
        this.port.apply(current, structuredClone(restored));
      }
      await this.finish(inputId, JSON.stringify(saved.input), saved.after, row.snapshot);
    } finally {
      this.busy = false;
    }
  }
}
