// `src/shared/lib/mockData.ts`** (연구 내용을 바탕으로 한 더미 데이터)
import type { Team, MatchResult, TeamSeasonRecord } from '../types';

export const TEAMS: Team[] = [
  {
    id: 'team-1',
    name: 'Alpha College',
    university: 'Alpha College',
    division: 'EUTTEUM',
    logoColor: '#4f46e5',
    founded: 1995,
  },
  {
    id: 'team-2',
    name: 'Beta University',
    university: 'Beta University',
    division: 'EUTTEUM',
    logoColor: '#10b981',
    founded: 2001,
  },
  {
    id: 'team-3',
    name: 'Gamma Tech',
    university: 'Gamma Tech',
    division: 'BEOGEUM',
    logoColor: '#f59e0b',
    founded: 1987,
  },
];

// 시뮬레이션을 위한 가상 경기 결과
export const MATCHES: MatchResult[] = [
  {
    id: 'match-1',
    homeTeamId: 'team-1',
    awayTeamId: 'team-2',
    homeScore: 3,
    awayScore: 2,
    isFinished: true,
  },
  {
    id: 'match-2',
    homeTeamId: 'team-2',
    awayTeamId: 'team-3',
    homeScore: 1,
    awayScore: 1,
    isFinished: true,
  },
  {
    id: 'match-3',
    homeTeamId: 'team-3',
    awayTeamId: 'team-1',
    homeScore: 0,
    awayScore: 2,
    isFinished: true,
  },
];

export const TEAM_RECORDS: TeamSeasonRecord[] = [
  {
    teamId: 'team-1',
    year: 2024,
    wins: 18,
    losses: 6,
    draws: 1,
    era: 2.91,
    ops: 0.802,
    stolenBases: 48,
    keyMoment: '6월 라이벌전 3연전 스윕으로 정규시즌 1위 확정',
    captains: ['박민수', '이도현'],
    players: [
      {
        id: 'p-alpha-1',
        teamId: 'team-1',
        name: '이도현',
        position: 'P',
        year: 2024,
        war: 3.1,
        era: 2.35,
        note: '82 IP · 102K · WHIP 1.02',
      },
      {
        id: 'p-alpha-2',
        teamId: 'team-1',
        name: '김하늘',
        position: 'SS',
        year: 2024,
        war: 2.7,
        ops: 0.874,
        avg: 0.321,
        slug: 0.512,
      },
      {
        id: 'p-alpha-3',
        teamId: 'team-1',
        name: '박민수',
        position: 'CF',
        year: 2024,
        war: 2.1,
        ops: 0.788,
        obp: 0.402,
        stolenBases: 26,
        note: '리드오프·주루 압박',
      },
    ],
  },
  {
    teamId: 'team-1',
    year: 2023,
    wins: 15,
    losses: 8,
    draws: 0,
    era: 3.24,
    ops: 0.755,
    stolenBases: 36,
    keyMoment: '후반기 불펜 보강 이후 8승 2패 마감',
    captains: ['조현우'],
    players: [
      {
        id: 'p-alpha-4',
        teamId: 'team-1',
        name: '조현우',
        position: 'C',
        year: 2023,
        war: 1.9,
        ops: 0.732,
        obp: 0.368,
        note: '투수 리드와 주루 저지로 수비 WAR 상승',
      },
      {
        id: 'p-alpha-5',
        teamId: 'team-1',
        name: '신지환',
        position: 'RF',
        year: 2023,
        war: 1.8,
        ops: 0.801,
        slug: 0.489,
      },
    ],
  },
  {
    teamId: 'team-2',
    year: 2024,
    wins: 16,
    losses: 9,
    draws: 0,
    era: 3.11,
    ops: 0.777,
    stolenBases: 41,
    keyMoment: '캡틴 교체 후 7연승으로 포스트시즌 진출',
    captains: ['윤태훈'],
    players: [
      {
        id: 'p-beta-1',
        teamId: 'team-2',
        name: '윤태훈',
        position: '2B',
        year: 2024,
        war: 2.5,
        ops: 0.821,
        obp: 0.392,
        stolenBases: 21,
      },
      {
        id: 'p-beta-2',
        teamId: 'team-2',
        name: '최민재',
        position: 'P',
        year: 2024,
        war: 2.3,
        era: 2.88,
        note: '76 IP · 88K · 피안타율 .218',
      },
      {
        id: 'p-beta-3',
        teamId: 'team-2',
        name: '정세윤',
        position: 'LF',
        year: 2024,
        war: 1.7,
        ops: 0.756,
        avg: 0.301,
      },
    ],
  },
  {
    teamId: 'team-2',
    year: 2023,
    wins: 12,
    losses: 11,
    draws: 1,
    era: 3.45,
    ops: 0.721,
    stolenBases: 30,
    keyMoment: '불펜 필승조 확립으로 클로즈드 아웃 성공률 80% 달성',
    captains: ['김세인'],
    players: [
      {
        id: 'p-beta-4',
        teamId: 'team-2',
        name: '김세인',
        position: 'C',
        year: 2023,
        war: 1.6,
        ops: 0.702,
        obp: 0.354,
      },
      {
        id: 'p-beta-5',
        teamId: 'team-2',
        name: '마준호',
        position: 'P',
        year: 2023,
        war: 1.5,
        era: 3.21,
        note: '멀티 롤 스윙맨으로 6승 3패',
      },
    ],
  },
  {
    teamId: 'team-3',
    year: 2024,
    wins: 13,
    losses: 11,
    draws: 1,
    era: 3.58,
    ops: 0.742,
    stolenBases: 37,
    keyMoment: '루키 타선 합류 후 팀 OPS .030 상승',
    captains: ['전유진'],
    players: [
      {
        id: 'p-gamma-1',
        teamId: 'team-3',
        name: '전유진',
        position: '1B',
        year: 2024,
        war: 2.2,
        ops: 0.835,
        slug: 0.521,
      },
      {
        id: 'p-gamma-2',
        teamId: 'team-3',
        name: '이수안',
        position: 'P',
        year: 2024,
        war: 1.9,
        era: 3.05,
        note: '파워 피처 → 구속 92mph, K/9 10.1',
      },
      {
        id: 'p-gamma-3',
        teamId: 'team-3',
        name: '박지온',
        position: 'CF',
        year: 2024,
        war: 1.4,
        ops: 0.711,
        stolenBases: 18,
      },
    ],
  },
  {
    teamId: 'team-3',
    year: 2023,
    wins: 10,
    losses: 13,
    draws: 1,
    era: 3.82,
    ops: 0.701,
    stolenBases: 28,
    keyMoment: '5월 이후 불펜 방어율 2.98로 반등하며 중위권 유지',
    captains: ['양서준'],
    players: [
      {
        id: 'p-gamma-4',
        teamId: 'team-3',
        name: '양서준',
        position: 'SS',
        year: 2023,
        war: 1.5,
        ops: 0.716,
        obp: 0.358,
      },
      {
        id: 'p-gamma-5',
        teamId: 'team-3',
        name: '문하림',
        position: 'P',
        year: 2023,
        war: 1.3,
        era: 3.42,
        note: '마무리 전환 후 세이브 9개',
      },
    ],
  },
];