#!/usr/bin/env python3
"""Generate SQL INSERT statements from crawler JSONL output files.

Usage:
    python scripts/generate_sql_dump.py /tmp/aubl_crawl_test --year 2024 > import_2024.sql

The generated SQL can be run on the server:
    mysql -u root webpage < import_2024.sql
"""
from __future__ import annotations

import json
import re
import sys
from collections import defaultdict
from decimal import Decimal, InvalidOperation
from pathlib import Path


def _strip_jersey(name: str) -> str:
    """'김민혁(52)' → '김민혁', '김동혁 (91)' → '김동혁'"""
    return re.sub(r"\s*[\(\(]\d+[\)\)]\s*$", "", name).strip()


def _esc(val: str | None) -> str:
    if val is None:
        return "NULL"
    return "'" + val.replace("\\", "\\\\").replace("'", "\\'") + "'"


def _num(val) -> str:
    if val is None:
        return "NULL"
    return str(val)


def _parse_innings(val) -> str:
    """Parse '22 ⅔' → '22.7'"""
    if val is None:
        return "NULL"
    s = str(val).strip()
    frac_map = {"⅓": ".3", "⅔": ".7", "1/3": ".3", "2/3": ".7"}
    for frac, dec in frac_map.items():
        if frac in s:
            whole = s.replace(frac, "").strip()
            return (whole or "0") + dec
    try:
        return str(float(s))
    except (ValueError, TypeError):
        return "NULL"


def main():
    if len(sys.argv) < 2:
        print("Usage: python generate_sql_dump.py <jsonl_dir> [--year YEAR]", file=sys.stderr)
        sys.exit(1)

    data_dir = Path(sys.argv[1])
    year = 2024
    if "--year" in sys.argv:
        idx = sys.argv.index("--year")
        year = int(sys.argv[idx + 1])

    out = sys.stdout
    out.write("-- AUBL Crawler Data Import\n")
    out.write(f"-- Year: {year}\n")
    out.write("-- Generated by generate_sql_dump.py\n\n")
    out.write("SET NAMES utf8mb4;\n")
    out.write("SET FOREIGN_KEY_CHECKS = 0;\n\n")

    # 1. SEASON
    out.write(f"-- Season\n")
    out.write(f"INSERT IGNORE INTO SEASON (year) VALUES ({year});\n")
    out.write(f"SET @season_id = (SELECT season_id FROM SEASON WHERE year = {year});\n\n")

    # 2. TEAM — collect unique teams
    teams_file = data_dir / "teams.jsonl"
    teams: dict[int, str] = {}  # team_idx → name
    team_id_map: dict[int, str] = {}  # team_idx → SQL variable name
    if teams_file.exists():
        with open(teams_file) as f:
            for line in f:
                t = json.loads(line)
                idx = t.get("team_idx")
                name = t.get("name")
                if idx and name:
                    teams[idx] = name

    out.write("-- Teams\n")
    for i, (idx, name) in enumerate(sorted(teams.items(), key=lambda x: x[0])):
        var = f"@team_{i}"
        team_id_map[idx] = var
        out.write(
            f"INSERT INTO TEAM (team_name, team_code) "
            f"SELECT {_esc(name)}, {_esc(str(idx))} FROM DUAL "
            f"WHERE NOT EXISTS (SELECT 1 FROM TEAM WHERE team_code = {_esc(str(idx))});\n"
        )
        out.write(f"SET {var} = (SELECT team_id FROM TEAM WHERE team_code = {_esc(str(idx))});\n")
    out.write("\n")

    # 3. PLAYER — collect unique players, strip jersey numbers
    players_file = data_dir / "players.jsonl"
    players: dict[str, dict] = {}  # name → {position, team_idx}
    if players_file.exists():
        with open(players_file) as f:
            for line in f:
                p = json.loads(line)
                name = _strip_jersey(p.get("name") or "")
                if not name:
                    continue
                if name not in players:
                    players[name] = {"position": p.get("position"), "team_idx": p.get("team_idx")}

    out.write("-- Players\n")
    for name, info in sorted(players.items()):
        pos = info.get("position")
        out.write(
            f"INSERT INTO PLAYER (player_name, position, is_player) "
            f"SELECT {_esc(name)}, {_esc(pos)}, 1 FROM DUAL "
            f"WHERE NOT EXISTS (SELECT 1 FROM PLAYER WHERE player_name = {_esc(name)});\n"
        )
    out.write("\n")

    # 4. TEAM_PLAYER — roster
    roster_file = data_dir / "roster_players.jsonl"
    out.write("-- Team-Player Roster\n")
    if roster_file.exists():
        with open(roster_file) as f:
            for line in f:
                r = json.loads(line)
                team_idx = r.get("team_idx")
                name = _strip_jersey(r.get("name") or "")
                if not name or not team_idx:
                    continue
                team_var = team_id_map.get(team_idx)
                if not team_var:
                    continue
                out.write(
                    f"INSERT INTO TEAM_PLAYER (team_id, player_id, season_id) "
                    f"SELECT {team_var}, "
                    f"(SELECT player_id FROM PLAYER WHERE player_name = {_esc(name)} LIMIT 1), "
                    f"@season_id FROM DUAL "
                    f"WHERE (SELECT player_id FROM PLAYER WHERE player_name = {_esc(name)} LIMIT 1) IS NOT NULL "
                    f"AND NOT EXISTS ("
                    f"SELECT 1 FROM TEAM_PLAYER WHERE team_id = {team_var} "
                    f"AND player_id = (SELECT player_id FROM PLAYER WHERE player_name = {_esc(name)} LIMIT 1) "
                    f"AND season_id = @season_id);\n"
                )
    out.write("\n")

    # 5. BATTER_STATS from league records
    league_bat_file = data_dir / "league_batting_records.jsonl"
    out.write("-- Batter Stats (league records)\n")
    if league_bat_file.exists():
        with open(league_bat_file) as f:
            data = json.loads(f.readline())
        payload = data.get("payload", {})
        records = []
        d = payload.get("data")
        if isinstance(d, dict):
            records = d.get("records", [])
        elif isinstance(d, list):
            records = d

        for rec in records:
            name = _strip_jersey(rec.get("mb_name") or rec.get("name") or "")
            team_name = rec.get("club_name") or rec.get("team_name") or ""
            if not name:
                continue

            gp = _num(rec.get("mygamecnt"))
            pa = _num(rec.get("bats"))
            ab = _num(rec.get("bat_cnt"))
            h = _num(rec.get("hit_cnt"))
            doubles = _num(rec.get("twobase"))
            triples = _num(rec.get("threebase"))
            hr = _num(rec.get("homerun"))
            rbi = _num(rec.get("bat_point"))
            sb = _num(rec.get("steal"))
            bb = _num(rec.get("fourball"))
            so = _num(rec.get("strikeout"))
            avg = _num(rec.get("hit_rate"))
            obp = _num(rec.get("base_rate"))
            slg = _num(rec.get("hitbase_rate"))
            ops = _num(rec.get("ops"))

            out.write(
                f"INSERT INTO BATTER_STATS "
                f"(tp_id, season_id, games_played, plate_appearance, at_bats, hits, "
                f"doubles, triples, home_runs, runs_batted_in, stolen_bases, walks, strikeouts, "
                f"batting_average, on_base_pct, slugging_pct, ops) "
                f"SELECT tp.tp_id, @season_id, {gp}, {pa}, {ab}, {h}, "
                f"{doubles}, {triples}, {hr}, {rbi}, {sb}, {bb}, {so}, "
                f"{avg}, {obp}, {slg}, {ops} "
                f"FROM TEAM_PLAYER tp "
                f"JOIN PLAYER p ON tp.player_id = p.player_id "
                f"JOIN TEAM t ON tp.team_id = t.team_id "
                f"WHERE p.player_name = {_esc(name)} "
                f"AND t.team_name = {_esc(team_name)} "
                f"AND tp.season_id = @season_id "
                f"AND NOT EXISTS ("
                f"SELECT 1 FROM BATTER_STATS bs WHERE bs.tp_id = tp.tp_id AND bs.season_id = @season_id) "
                f"LIMIT 1;\n"
            )
    out.write("\n")

    # 6. PITCHER_STATS from league records
    league_pitch_file = data_dir / "league_pitching_records.jsonl"
    out.write("-- Pitcher Stats (league records)\n")
    if league_pitch_file.exists():
        with open(league_pitch_file) as f:
            data = json.loads(f.readline())
        payload = data.get("payload", {})
        records = []
        d = payload.get("data")
        if isinstance(d, dict):
            records = d.get("records", [])
        elif isinstance(d, list):
            records = d

        for rec in records:
            name = _strip_jersey(rec.get("mb_name") or rec.get("name") or "")
            team_name = rec.get("club_name") or rec.get("team_name") or ""
            if not name:
                continue

            gp = _num(rec.get("mygamecnt"))
            ip = _parse_innings(rec.get("inning"))
            w = _num(rec.get("win"))
            l = _num(rec.get("lose"))
            sv = _num(rec.get("save"))
            hld = _num(rec.get("hold"))
            ha = _num(rec.get("nohit"))
            runs = _num(rec.get("lost_point"))
            er = _num(rec.get("self_point"))
            hra = _num(rec.get("nohomerun"))
            bb = _num(rec.get("fourball"))
            so = _num(rec.get("strikeout"))
            hbp = _num(rec.get("deadball"))
            wp = _num(rec.get("wildpitch"))
            bk = _num(rec.get("balk"))
            era = _num(rec.get("def_rate"))
            whip = _num(rec.get("whip"))
            k9 = _num(rec.get("strikeout_rate"))

            out.write(
                f"INSERT INTO PITCHER_STATS "
                f"(tp_id, season_id, games_played, innings_pitched, wins, losses, saves, holds, "
                f"hits_allowed, runs_allowed, earned_runs, home_runs_allow, walks_allowed, strikeouts, "
                f"hit_batters, wild_pitches, balks, era, whip, k_per_9) "
                f"SELECT tp.tp_id, @season_id, {gp}, {ip}, {w}, {l}, {sv}, {hld}, "
                f"{ha}, {runs}, {er}, {hra}, {bb}, {so}, "
                f"{hbp}, {wp}, {bk}, {era}, {whip}, {k9} "
                f"FROM TEAM_PLAYER tp "
                f"JOIN PLAYER p ON tp.player_id = p.player_id "
                f"JOIN TEAM t ON tp.team_id = t.team_id "
                f"WHERE p.player_name = {_esc(name)} "
                f"AND t.team_name = {_esc(team_name)} "
                f"AND tp.season_id = @season_id "
                f"AND NOT EXISTS ("
                f"SELECT 1 FROM PITCHER_STATS ps WHERE ps.tp_id = tp.tp_id AND ps.season_id = @season_id) "
                f"LIMIT 1;\n"
            )
    out.write("\n")

    # 7. GAME + BATTER_GAME_LOG + PITCHER_GAME_LOG from matches/batting_stats/pitching_stats
    matches_file = data_dir / "matches.jsonl"
    batting_file = data_dir / "batting_stats.jsonl"
    pitching_file = data_dir / "pitching_stats.jsonl"

    # Load matches
    matches: dict[int, dict] = {}
    if matches_file.exists():
        with open(matches_file) as f:
            for line in f:
                m = json.loads(line)
                gidx = m.get("game_idx")
                if gidx:
                    matches[gidx] = m

    # Load batting stats by game_idx
    batting_by_game: dict[int, list] = defaultdict(list)
    if batting_file.exists():
        with open(batting_file) as f:
            for line in f:
                b = json.loads(line)
                gidx = b.get("game_idx")
                if gidx:
                    batting_by_game[gidx].append(b)

    # Load pitching stats by game_idx
    pitching_by_game: dict[int, list] = defaultdict(list)
    if pitching_file.exists():
        with open(pitching_file) as f:
            for line in f:
                p = json.loads(line)
                gidx = p.get("game_idx")
                if gidx:
                    pitching_by_game[gidx].append(p)

    out.write("-- Games and Game Logs\n")
    for gidx, match in sorted(matches.items()):
        home_idx = match.get("home_team_idx")
        away_idx = match.get("away_team_idx")
        home_var = team_id_map.get(home_idx, "NULL")
        away_var = team_id_map.get(away_idx, "NULL")
        home_score = _num(match.get("home_runs"))
        away_score = _num(match.get("away_runs"))

        out.write(f"\n-- Game {gidx}\n")
        out.write(
            f"INSERT INTO GAME (season_id, game_date, game_number, home_team, away_team, home_score, away_score) "
            f"SELECT @season_id, CURDATE(), {gidx}, {home_var}, {away_var}, {home_score}, {away_score} "
            f"FROM DUAL WHERE NOT EXISTS ("
            f"SELECT 1 FROM GAME WHERE season_id = @season_id AND game_number = {gidx});\n"
        )
        out.write(f"SET @game_id = (SELECT game_id FROM GAME WHERE season_id = @season_id AND game_number = {gidx});\n")

        # Batter game logs — ensure TEAM_PLAYER + BATTER_STATS exist first
        for b in batting_by_game.get(gidx, []):
            pname = b.get("player_name") or ""
            team_idx = b.get("team_idx")
            side = b.get("team_side")
            t_var = team_id_map.get(team_idx, "NULL")
            if t_var == "NULL" or not pname:
                continue

            # Ensure TEAM_PLAYER row exists
            out.write(
                f"INSERT INTO TEAM_PLAYER (team_id, player_id, season_id) "
                f"SELECT {t_var}, p.player_id, @season_id "
                f"FROM PLAYER p WHERE p.player_name = {_esc(pname)} "
                f"AND NOT EXISTS (SELECT 1 FROM TEAM_PLAYER tp2 "
                f"WHERE tp2.team_id = {t_var} AND tp2.player_id = p.player_id "
                f"AND tp2.season_id = @season_id) LIMIT 1;\n"
            )
            # Ensure BATTER_STATS row exists
            out.write(
                f"INSERT INTO BATTER_STATS (tp_id, season_id) "
                f"SELECT tp.tp_id, @season_id FROM TEAM_PLAYER tp "
                f"JOIN PLAYER p ON tp.player_id = p.player_id "
                f"WHERE p.player_name = {_esc(pname)} AND tp.team_id = {t_var} "
                f"AND tp.season_id = @season_id "
                f"AND NOT EXISTS (SELECT 1 FROM BATTER_STATS bs "
                f"WHERE bs.tp_id = tp.tp_id AND bs.season_id = @season_id) LIMIT 1;\n"
            )
            # Insert game log
            out.write(
                f"INSERT INTO BATTER_GAME_LOG "
                f"(game_idx, team_side, team_idx, player_idx, batter_stat_id, "
                f"player_name, player_position, at_bats, runs, hits, rbi, walks, strikeouts) "
                f"SELECT @game_id, {_esc(side)}, {t_var}, "
                f"(SELECT player_id FROM PLAYER WHERE player_name = {_esc(pname)} LIMIT 1), "
                f"(SELECT bs.batter_stat_id FROM BATTER_STATS bs "
                f"JOIN TEAM_PLAYER tp ON bs.tp_id = tp.tp_id "
                f"JOIN PLAYER p ON tp.player_id = p.player_id "
                f"WHERE p.player_name = {_esc(pname)} AND tp.team_id = {t_var} "
                f"AND bs.season_id = @season_id LIMIT 1), "
                f"{_esc(pname)}, {_esc(b.get('player_position'))}, "
                f"{_num(b.get('at_bats'))}, {_num(b.get('runs'))}, {_num(b.get('hits'))}, "
                f"{_num(b.get('rbi'))}, {_num(b.get('walks'))}, {_num(b.get('strikeouts'))} "
                f"FROM DUAL WHERE @game_id IS NOT NULL "
                f"AND (SELECT bs.batter_stat_id FROM BATTER_STATS bs "
                f"JOIN TEAM_PLAYER tp ON bs.tp_id = tp.tp_id "
                f"JOIN PLAYER p ON tp.player_id = p.player_id "
                f"WHERE p.player_name = {_esc(pname)} AND tp.team_id = {t_var} "
                f"AND bs.season_id = @season_id LIMIT 1) IS NOT NULL;\n"
            )

        # Pitcher game logs — ensure TEAM_PLAYER + PITCHER_STATS exist first
        for p in pitching_by_game.get(gidx, []):
            pname = p.get("player_name") or ""
            team_idx = p.get("team_idx")
            side = p.get("team_side")
            t_var = team_id_map.get(team_idx, "NULL")
            if t_var == "NULL" or not pname:
                continue

            ip_val = p.get("innings_pitched")
            if ip_val is not None:
                try:
                    fval = float(ip_val)
                    whole = int(fval)
                    frac = fval - whole
                    if frac >= 0.5:
                        ip_str = f"{whole}.7"
                    elif frac >= 0.2:
                        ip_str = f"{whole}.3"
                    else:
                        ip_str = f"{whole}.0"
                except (ValueError, TypeError):
                    ip_str = "NULL"
            else:
                ip_str = "NULL"

            # Ensure TEAM_PLAYER row exists
            out.write(
                f"INSERT INTO TEAM_PLAYER (team_id, player_id, season_id) "
                f"SELECT {t_var}, p.player_id, @season_id "
                f"FROM PLAYER p WHERE p.player_name = {_esc(pname)} "
                f"AND NOT EXISTS (SELECT 1 FROM TEAM_PLAYER tp2 "
                f"WHERE tp2.team_id = {t_var} AND tp2.player_id = p.player_id "
                f"AND tp2.season_id = @season_id) LIMIT 1;\n"
            )
            # Ensure PITCHER_STATS row exists
            out.write(
                f"INSERT INTO PITCHER_STATS (tp_id, season_id) "
                f"SELECT tp.tp_id, @season_id FROM TEAM_PLAYER tp "
                f"JOIN PLAYER p ON tp.player_id = p.player_id "
                f"WHERE p.player_name = {_esc(pname)} AND tp.team_id = {t_var} "
                f"AND tp.season_id = @season_id "
                f"AND NOT EXISTS (SELECT 1 FROM PITCHER_STATS ps "
                f"WHERE ps.tp_id = tp.tp_id AND ps.season_id = @season_id) LIMIT 1;\n"
            )
            # Insert game log
            out.write(
                f"INSERT INTO PITCHER_GAME_LOG "
                f"(game_idx, team_side, team_idx, player_idx, pitcher_stat_id, "
                f"player_name, innings_pitched, hits_allowed, runs_allowed, earned_runs, walks, strikeouts) "
                f"SELECT @game_id, {_esc(side)}, {t_var}, "
                f"(SELECT player_id FROM PLAYER WHERE player_name = {_esc(pname)} LIMIT 1), "
                f"(SELECT ps.pitcher_stat_id FROM PITCHER_STATS ps "
                f"JOIN TEAM_PLAYER tp ON ps.tp_id = tp.tp_id "
                f"JOIN PLAYER p ON tp.player_id = p.player_id "
                f"WHERE p.player_name = {_esc(pname)} AND tp.team_id = {t_var} "
                f"AND ps.season_id = @season_id LIMIT 1), "
                f"{_esc(pname)}, {ip_str}, "
                f"{_num(p.get('hits_allowed'))}, {_num(p.get('runs_allowed'))}, "
                f"{_num(p.get('earned_runs'))}, {_num(p.get('walks'))}, {_num(p.get('strikeouts'))} "
                f"FROM DUAL WHERE @game_id IS NOT NULL "
                f"AND (SELECT ps.pitcher_stat_id FROM PITCHER_STATS ps "
                f"JOIN TEAM_PLAYER tp ON ps.tp_id = tp.tp_id "
                f"JOIN PLAYER p ON tp.player_id = p.player_id "
                f"WHERE p.player_name = {_esc(pname)} AND tp.team_id = {t_var} "
                f"AND ps.season_id = @season_id LIMIT 1) IS NOT NULL;\n"
            )

    out.write("\n")
    out.write("SET FOREIGN_KEY_CHECKS = 1;\n")
    out.write("-- Done.\n")


if __name__ == "__main__":
    main()
